image: lawngnome/ubuntu:precise
manifests:
    -
        image: ubuntu:precise
        platform:
            architecture: amd64
            os: linux
    -
        image: armhf/ubuntu:precise
        platform:
            architecture: arm
            os: linux
